# Data settings
network: 'study_area'

#Hyperparameters
epochs                 : 500
switch_epoch           : 50

min_expected_loss      : 100

balance_ratio          : 0.5
batch_size             : 16
edge_input_list        : 'length,diameter,node_slope, conduit_slope,aprox_conduit_volume,in_offset,out_offset' #aprox_conduit_volume,
gamma_loss             : 1.00
gamma_scheduler        : 1.00
hidden_dim             : 64
learning_rate          : 0.00025
model_name             : Edge_STGCN
n_hidden_layers        : 1
n_gcn_layers           : 11
non_linearity          : "PReLU"
num_events_training    : 70
num_events_validation  : 20
num_events_testing     : 10

prediction_steps       : 1
seed                   : 5
skip_alpha             : 0.8
steps_behind           : 24
steps_ahead            :
  - 6
  - 12
steps_ahead_validation : 12
weight_decay           : 0.01
variance_threshold     : 0.05
monitored_nodes        : [195]

k_hops                 : 1
eps_gnn                : 0.5


use_saved_training_windows  : True
use_saved_validation_windows: True

training_windows_names:
  - 'study_area_tra_windows.pk'
  - 'study_area_tra_windows.pk'
validation_windows_name : 'study_area_val_windows.pk'

use_training_simulations: True
use_validation_simulations: True
use_testing_simulations: True

use_pre_trained_weights: False
requires_freezing:  True
pre_trained_weights: 'best_model_realdata_11layer_24nodes_50%.pt' #If use_pre_trained_weights is false, this line is ignored

use_trained_weights: True
trained_weights: 'best_model_realdata_11layer_24nodes_50%.pt' ##best_model1,12nodes,eval results 0.674,0.704,3 train

use_saved_normalizer: True
saved_normalizer_name: "normalizer_saved.pk"
normalizer_name: "Normalizer"

use_saved_normalized_windows_dataset: True
saved_normalized_training_dataset_name: "study_area_normalized_training_dataset.pk"
saved_normalized_validation_dataset_name: "study_area_normalized_validation_dataset.pk"


trainer_name: 'Renconstrcution_Trainer'
node_loss_weight: 1
edge_loss_weight: 1

abs_flows: False

